name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 001-new-feature
    # Review gh-pages branches manually before deploying.
    paths:
      - 'my-docusaurus-site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'my-docusaurus-site/package-lock.json'
      
      - name: Install dependencies
        run: cd my-docusaurus-site && npm install
      
      - name: Build
        run: cd my-docusaurus-site && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-docusaurus-site/build
          publish_branch: gh-pages
          cname: ''
